services:
  - type: web
    name: txt-extractor-pw
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/rohanh6609/TXT-EXTRACTOR
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
